### ISSUE TITLE
GUI doesn't work

### ISSUE THREAD

**Issue by ArikSquad** [Lenni0451/SpigotPluginManager#28]
Gui really doesn't work on 1.20.1

Using latest paper 1.20.1

**Comment by Lenni0451** [comment]
Could you please give me more information about the used server software and what exactly does not work?

**Comment by xarkenz** [comment]
I thought I'd add to this. I'm using a `paper-1.20.1-43` server on my local machine with PluginManager 2.8.0 installed as a plugin. The core plugin has no issue when loading, but as soon as it checks for a newer version of itself, it seems to find a "newer" version, which is just the 2.8.0 version number with a lot of HTML garbage attached. Seems to indicate some sort of bug in the process of web scraping, if that's what is being used to detect the latest available version.

![image](https://github.com/Lenni0451/SpigotPluginManager/assets/46010001/400a2f20-abac-420b-b1f7-c2ff58902b81)

It tries to download this "version" and reloads the plugin, but then crashes due to an "Invalid plugin file." Not sure if this is what @ArikSquad is talking about, but this is the roadblock I've run into.

![image](https://github.com/Lenni0451/SpigotPluginManager/assets/46010001/2393ae0e-fe0e-450e-aa9c-67c9d29ccbad)

**Comment by ArikSquad** [comment]
> It tries to download this "version" and reloads the plugin, but then crashes due to an "Invalid plugin file." Not sure if this is what @ArikSquad is talking about, but this is the roadblock I've run into.
> 

The initial issue was that loading and unloading were not working on paper, (it wasn't 1.20) 

Also super weird issue tho, it seems it just finds it from the web, couldn't it use some apis?

(Hopefully the block reply works)

**Comment by Lenni0451** [comment]
> I thought I'd add to this. I'm using a `paper-1.20.1-43` server on my local machine with PluginManager 2.8.0 installed as a plugin. The core plugin has no issue when loading, but as soon as it checks for a newer version of itself, it seems to find a "newer" version, which is just the 2.8.0 version number with a lot of HTML garbage attached. Seems to indicate some sort of bug in the process of web scraping, if that's what is being used to detect the latest available version.
> 
> ![image](https://user-images.githubusercontent.com/46010001/247698351-400a2f20-abac-420b-b1f7-c2ff58902b81.png)
> 
> It tries to download this "version" and reloads the plugin, but then crashes due to an "Invalid plugin file." Not sure if this is what @ArikSquad is talking about, but this is the roadblock I've run into.
> 
> ![image](https://user-images.githubusercontent.com/46010001/247698664-2393ae0e-fe0e-450e-aa9c-67c9d29ccbad.png)

The updater seems to be broken since the last version. I'm working on a fix for that

**Comment by xarkenz** [comment]
I think I've found where the issue is. Here is the `DownloadUtils.getNewestVersion()` method:
```java
public class DownloadUtils {
    /* other methods not shown */
    public static String getNewestVersion() throws IOException {
        HttpURLConnection connection = openConnection("https://github.com/Lenni0451/SpigotPluginManager/releases/latest");
        if (connection == null) throw new IOException();

        String response = readString(connection);

        String urlBase = "https://github.com/Lenni0451/SpigotPluginManager/releases/tag/";
        String version = response.substring(response.indexOf(urlBase) + urlBase.length());
        version = version.substring(0, version.indexOf("&"));
        return version;
    }
}
```
The value of `version` is first a substring of `response`, the HTML content of the whole page. `version` is then set to a substring of that ending at the first `&` it finds. Looking at the HTML, this lines up with the erroneous output we get. The easiest solution I can think of is just defining `version` like so:
```java
String urlBase = /* ... */;
int versionStart = response.indexOf(urlBase) + urlBase.length();
String version = response.substring(versionStart, response.indexOf('"', versionStart));
return version;
```

**Comment by Lenni0451** [comment]
I am now using the api instead of doing web scraping. Should be working way better.

**Comment by xarkenz** [comment]
Sweet. Hopefully that should prevent you from having to deal with this sort of issue again ;) Thanks so much for your help!

**Comment by Lenni0451** [comment]
Yeah, I hope so. The plugin not being able to reload is actually another bug I have to fix. Then I will release a new update

**Comment by Lenni0451** [comment]
The updater has been fixed with version 2.8.1.

@ArikSquad The gui seems to be working fine for me. What exactly is not working?

**Comment by ArikSquad** [comment]
> The updater has been fixed with version 2.8.1.
> 
> @ArikSquad The gui seems to be working fine for me. What exactly is not working?

I'm not sure if it's in latesy ver but atleast in 2.8.0 when clicking a gui item it just picks it up and makes an error message in chat (sorry for not having it here since I'm away from computer rn)

**Comment by Lenni0451** [comment]
If you can reproduce this please send the error. I tested it and it seemed to be working without any problems.

**Comment by ArikSquad** [comment]
Not happening in latest versions
