### ISSUE TITLE
No Instructions for Config File

### ISSUE THREAD

**Issue by CiaranGruber** [Lenni0451/SpigotPluginManager#3]
Sorry if there is a place but I've searched around and haven't found how to use the installed.yml file. As a result, when I try to update plugins, it says  "XXX is not in the config file"

**Comment by Lenni0451** [comment]
Hi,
the update feature is not fully finished yet. It currently only works with plugins you have downloaded from spigotmc using the '/pm download spigot' feature of SpigotPluginManager. Since I have lost the interest in coding plugins a bit I currently sadly can't say, when the feature will be fully implemented. It is working but only as I said when downloaded directly.

**Comment by CiaranGruber** [comment]
OK thanks, I mean most of my plugins came from Spigot anyway so just reinstalling via the PluginManager should be fine shouldn't it? And will it just install as normal just with an extra log file (ie. removing PluginManager shouldn't affect the installed plugins)?

**Comment by Lenni0451** [comment]
Yes, you could reinstall them using the PluginManager and everything should work fine. The plugins themselves are independant from the PluginManager itself. Removing the PluginManager results in you no longer being able to use it but all the other plugins remain untouched.
